name: I Found
favicon: null
layout_spectrum: 1
typography_spectrum: 0.16011
title: "Tech's cool - up to a point!"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffeff'
    - '#14323a'
    - '#00001f'
    - '#c4b98c'
    - '#8b8a6e'
  brandStrength: 0.5
  lightness: 0.548093902412802
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
